// <auto-generated />
using System;
using AspCore1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspCore1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspCore1.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AspCore1.Models.Marks", b =>
                {
                    b.Property<int>("MarkID")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID_1")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID_2")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID_3")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID_4")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID_5")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID_6")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName_3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName_4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName_5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName_6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Subject_1_Mark")
                        .HasColumnType("int");

                    b.Property<int>("Subject_2_Mark")
                        .HasColumnType("int");

                    b.Property<int>("Subject_3_Mark")
                        .HasColumnType("int");

                    b.Property<int>("Subject_4_Mark")
                        .HasColumnType("int");

                    b.Property<int>("Subject_5_Mark")
                        .HasColumnType("int");

                    b.Property<int>("Subject_6_Mark")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("MarkID");

                    b.HasIndex("StudentID");

                    b.ToTable("marks");
                });

            modelBuilder.Entity("AspCore1.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AspCore1.Models.Marks", b =>
                {
                    b.HasOne("AspCore1.Models.Student", "Student")
                        .WithMany("marks")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AspCore1.Models.Student", b =>
                {
                    b.HasOne("AspCore1.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AspCore1.Models.Department", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("AspCore1.Models.Student", b =>
                {
                    b.Navigation("marks");
                });
#pragma warning restore 612, 618
        }
    }
}
